# Generated by Django 6.0.7 on 2026-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
